# Generated by Django 3.0.5 on 2021-04-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_code', models.IntegerField()),
                ('office_worker_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreRentalPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_code', models.IntegerField()),
                ('deactivate_under_deposit', models.IntegerField()),
                ('deactivate_under_rent', models.IntegerField()),
            ],
        ),
    ]
